language: python

services:
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis"


env:
    - TRAVIS: True

addons:
    postgresql: "9.5"
    apt:
     packages:
     - postgresql-9.5-postgis-2.3

install:
  - pip install -r requirements.txt

script:
  ls