version: '3'

services:
  db:
    image: mdillon/postgis
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "geo"
    volumes:
      - ./data:/var/lib/postgresql/data

  memcached:
    image: memcached:alpine

  web:
    environment:
      DBNAME: postgres
      DBUSER: postgres
      DBPASS: 'geo'
      DBHOST: 'db'
    build: .
    restart: on-failure
    command: bash docker-entrypoint.sh
    volumes:
      - .:/opt/app
    ports:
      - "8002:8002"
    depends_on:
      - db