version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: "geo"
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    environment:
      DBNAME: postgres
      DBUSER: postgres
      DBPASS: 'geo'
      DBHOST: 'db'
    build: .
    command: bash docker-entrypoint.sh
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db