# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 06:39
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('world', '0001_initial'), ('world', '0002_auto_20170406_2105'), ('world', '0003_auto_20170407_1108'), ('world', '0004_auto_20170407_1832')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('endyear', models.DateField(null=True)),
                ('startyear', models.DateField(default=datetime.date(1000, 1, 1))),
            ],
        ),
    ]
