# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0001_squashed_0004_auto_20170407_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldborder',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
