# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='endYear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='worldborder',
            name='startYear',
            field=models.DateField(default=datetime.date(1000, 1, 1)),
        ),
    ]
