# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20170914_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
