# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20170406_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='endYear',
            new_name='endyear',
        ),
        migrations.RenameField(
            model_name='worldborder',
            old_name='startYear',
            new_name='startyear',
        ),
    ]
